
name: bagle 

channels:
    - conda-forge
    - defaults

dependencies:
    - ipywidgets==7.6
    - viola==0.3.0
    - python
    - astropy
    - numpydoc 
    - matplotlib
    - numpy
    - celerite
    - ephem
    - joblib
    - jplephem
    - graphviz 
    - pymultinest
    - dynesty
    - pytest
    - mpi4py
    - pip:
        - sphinxcontrib-video

